### ISSUE TITLE
fixing AppVeyor

### ISSUE THREAD

**Issue by IndrajeetPatil** [esqLABS/esqlabsR#120]
@msevestre I am [seeing](https://ci.appveyor.com/project/StephanSchaller/esqlabsr/builds/41466745) the same error you were seeing for `{ospsuite}`'s `AppVeyor` builds. 

```r
-- Error (test-utilities-individual.R:29:3): It create IndividualCharacteristics with the correct values --
  Error in `initPKSim()`: Could not find an installation of PK-Sim on the machine. 
  Please install the OSPSuite or use 'initPKSim()' to specify the installation path
```

How did you fix it?

**Comment by msevestre** [comment]
here you are are installing v10 of `ospsuite` package
https://github.com/esqLABS/esqlabsR/blob/develop/appveyor.yml#L55

But the script installs the latest PKSim (v11)
https://github.com/esqLABS/esqlabsR/blob/develop/rakefile.rb#L21

Ths lines make sense in OSPSuite.R package but in a dependent package, I would rely on downloading from github tag instead (and modify the code slightly as what you download is already an msi package)

**Comment by msevestre** [comment]
or you bump to v11 of ospsuite package in dependency

**Comment by IndrajeetPatil** [comment]
But how can I download the v11 of ospsuite?

Because the binary version is not available in releases: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/releases

And if I use `remotes::install_github`, I remember that there was some GitHub PAT related issue.

**Comment by msevestre** [comment]
Ah ah yes...maybe we need to fix this GitHub Pat issue bullshit

**Comment by msevestre** [comment]
You could also download form appveyor directly

**Comment by IndrajeetPatil** [comment]
Okay, lemme give that a try!
