### ISSUE TITLE
calculateMeans: allow conversion between dimensions?

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#147]
E.g., one DataSet is given in µmol, the other in g. Convert?

When different DataSets do have different MW???

**Comment by StephanSchaller** [comment]
?

**Comment by PavelBal** [comment]
If MW is given: Check whether all MW values are the same, otherwise error.

**Comment by PavelBal** [comment]
Or: MW as input?

**Comment by PavelBal** [comment]
Short update: for unit conversion, ALWAYS use MW stored in the respective `DataSet`.
Function argument: `outputMW` or something like this.

Use cases:
- All data sets have the same MW (or MW is NULL) and `outputMW` is not specified -> Output MW is the MW of the data sets
- All data sets have the same MW (or MW is NULL) and `outputMW` is specified -> For unit conversion, use MW stored in the respective data set, MW of the output data set is `outputMW` (inconsistent with input, but whatever)
- Data sets have different MW, `outputMW` is specified -> For unit conversion, use MW stored in the respective data set, MW of the output data set is `outputMW`
- Data sets have different MW, `outputMW` is not specified -> Error
