### ISSUE TITLE
Release 2.0.0 missing the binaries

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#149]
The release does not contain the *.zip of the package. Please compile and attach.

**Comment by PavelBal** [comment]
Very high prio.

And I cannot build it with the current `ospsuite-r` - does it have something to do with the utils package? I thought this should not be a breaking change?

```
==> devtools::document(roclets = c('rd', 'collate', 'namespace'))

i Updating esqlabsR documentation
i Loading esqlabsR
Error in enum(list("Simulated", "Observed", "Unspecified")) (from XYData.R#354) : 
  could not find function "enum"
Calls: suppressPackageStartupMessages ... withr_with_dir -> force -> source_many -> source_one -> eval -> eval
Execution halted

Exited with status 1.
```

**Comment by PavelBal** [comment]
Also rClr is outdated (0.9.1 is the current one)

**Comment by PavelBal** [comment]
Also add list of all dependencies that must be installed by the user.

**Comment by IndrajeetPatil** [comment]
> Also rClr is outdated (0.9.1 is the current one)

Done.

> Also add list of all dependencies that must be installed by the user

Done.

> I thought this should not be a breaking change?

It shouldn't have been, but only if we are using a version of `{ospsuite}` that relies on `{ospsuite.utils}`. And I now realize that the `{ospsuite}` we have attached doesn't. 😞 

@msevestre Can we make a new release of `{ospsuite}`? 
We need to attach a version of the `{ospsuite}` package to this release that relies on `{ospsuite.utils}`.

**Comment by IndrajeetPatil** [comment]
We can't release `11.0`, of course. But I was thinking either a minor or a patch release that contains [this](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/commit/96919d2a0e58586d8114b554a15f152488ece988) commit.

**Comment by PavelBal** [comment]
> Also add list of all dependencies that must be installed by the user
> 
> Done.

This must be done for the release, and only list there the packages that are actually required (maybe with the call to `install.packages()`). It must be straightforward to install everything if the user starts with a fresh R installation.

> . And I now realize that the {ospsuite} we have attached doesn't.

THe attached version is pre-utils

> We need to attach a version of the {ospsuite} package to this release that relies on {ospsuite.utils}.

No we dont! The whole purpose of this release was that it works with the official, release `ospsuite` v10.

**Comment by IndrajeetPatil** [comment]
> No we dont! The whole purpose of this release was that it works with the official, release ospsuite v10.

Ah, yes. True that!

> could not find function "enum"

But then I this error makes no sense because `enum` hasn't been removed from the released version of `{ospsuite}`. 🤔 

I also downloaded the released version of `{ospsuite}`, but get the following error. Trying to figure out how to get rid of it now.

```r
> library(ospsuite)
Loading required package: rClr
Loading the dynamic library for Microsoft .NET runtime...
Loaded Common Language Runtime version 4.0.30319.42000

Error: package or namespace load failed for ‘ospsuite’:
 .onLoad failed in loadNamespace() for 'ospsuite', details:
  call: rClr::clrLoadAssembly(filePathFor("OSPSuite.R.dll"))
  error: Failure in rclr_ms_call_static_method, but could not retrieve an error message
```
