### ISSUE TITLE
SensitivityAnalysis: `sensitivityCalculation` should return `SimulationResults` objects

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#153]
The output of the `sensivitiyCalculation` function is now:

`return(list("tsData" = tsData, "pkData" = pkData))`

The size of `tsData` in the default example is 2.7 Mb, which is crazy! I think it is better to return the `SimulationResults` object that are returned by 

`  simResultsBatch <- unlist(runSimulationBatches(simBatch))`

`sensivitiyCalculation` should return a named list with two entries - `SimulationResults` and `pkData`.

`SimulationResults` should be a named list with entries for each varied parameter, with parameter path being the name of the entry (e.g. "Aciclovir|Lipophilicity",
  "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
  "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction")

the entries are basically what is generated by `simResultsBatch <- unlist(runSimulationBatches(simBatch))`. The names of `simResultsBatch` are by default the Ids of the runs, looks like

```
simResultsBatch
$`5d5c965e-833a-424b-8521-11328ae74acf`
SimulationResults: 
   Number of individuals: 1 

$`e73e9e66-aa47-4dab-b68c-e2d6be734874`
SimulationResults: 
   Number of individuals: 1 
```

the IDs should be replaced by the scale factor of the parameter that has been used for this run. In my version of the script, I have been keeping track of mapping of run IDs to parameter values by

```
    valuesIds <- lapply(parVarList, \(value){
      values <- defaultParamValues
      values[[param$path]] <- value
      simBatch$addRunValues(unlist(values, use.names = FALSE))
    })
    names(valuesIds) <- parVarList
```

So the end the output will contain all required information: all generated `SimulationResults` objects, sorted by parameter paths sorted by parameter scaling values. With object size probably less then 1 Mb because we are only storing references to .NET objects.

**Comment by IndrajeetPatil** [comment]
These are very different specifications for these functions than what's mentioned in #146. 

Should these changes take place for WP6 for BI, or only for `{esqlabsR}` package functions?

Also, what should happen with the plotting functions then? They currently expect a dataframe, not `SimulationResults`.

**Comment by PavelBal** [comment]
> Also, what should happen with the plotting functions then? They currently expect a dataframe, not SimulationResults.

Well they must be adjusted accordingly, otherwise there are useless :D You just have move the data extraction to (or repeat it in) plotting functions.

**Comment by IndrajeetPatil** [comment]
This seems to be a function of how long the `variationRange` vector is:

Here is a reproducible example:

With default range, it's 2.8 MB
With just 3 values, it drops to 450 KB.
For a vector with 1000 values, yes, this is going to blow up in size.

``` r
library(ospsuite)
library(dplyr)
library(esqlabsR)

simPath <- system.file("extdata", "Aciclovir.pkml", package = "esqlabsR")
simulation <- loadSimulation(simPath)
outputPaths <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
parameterPaths <- c(
  "Aciclovir|Lipophilicity",
  "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
  "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction"
)

# extract the results into a list of dataframes
df_list <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths
)

lobstr::obj_size(df_list$tsData)
#> 2,802,128 B


df2_list <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths,
  variationRange = c(0.1, 1, 2)
)

lobstr::obj_size(df2_list$tsData)
#> 445,328 B
```

<sup>Created on 2022-02-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

I think instead of creating these dataframes in the global environment, we should be creating them on stack, save data and save plots on secondary storage devices, and as the function quits, all this data will be deleted. That is `sensitivityCalculation()`, when called and if the corresponding arguments are set to do so, will carry out sensitivity analysis **and** save table and plots, so no need for the user to separately call plotting functions. The plotting functions will still be exported, though, in case the user wants to create custom plots.

This way, the function API remains quite simple, we don't strain RAM, and we don't need to have argument inconsistency across plotting functions, where one expects a dataframe, while the other an R6 object.

We can discuss this in person, but just wanted to have my thoughts in writing.

**Comment by PavelBal** [comment]
>This seems to be a function of how long the variationRange vector is:

Of course, the more scale factors, the more simulations are created. It will also scale linearly with the number of selected outputs.

> save data and save plots on secondary storage devices

Temporary files? This is definitely an overkill for such a "simple" task.

> That is sensitivityCalculation(), when called and if the corresponding arguments are set to do so, will carry out sensitivity analysis and save table and plots, so no need for the user to separately call plotting functions. 

We discussed this and it is not ideal because we definitely want to give some flexibility to change e.g. axis scaling, and these can be different for time profiles and spider plots, so I still prefer to have them separated.

> and we don't need to have argument inconsistency across plotting functions, where one expects a dataframe, while the other an R6 object.

Well the input can just be the output of `sensitivityCalculation`, so it doesn't really matter for the user. He won't even notice whether there are data frames or objects or whatever.

**Comment by IndrajeetPatil** [comment]
Okay, so if I understand you correctly, the final API you are proposing for sensitivity analysis will look like this:

```r
results <- sensitivityCalculation(simulation, outputPaths, parameterPaths)

sensivitityTimeProfiles(results$SimulationResults) 
sensitivitySpiderPlot(results$pkData) 
```

I tried implementing this, but here is the problem.

For concentration plot, since we are now providing a list of simulation results objects, the problem occurs here:

> You just have move the data extraction to (or repeat it in) plotting functions.

The `results$SimulationResults` contains no information about [`Parameter`](https://www.open-systems-pharmacology.org/OSPSuite-R/reference/Parameter.html) objects representing parameter paths. And these details are needed to create this plot. Before, when I was passing the dataframe, it contained all the details about parameter paths.

I don't see any way to make this work. Any ideas?

**Comment by PavelBal** [comment]
> Okay, so if I understand you correctly, the final API you are proposing for sensitivity analysis will look like this:

Almost:

```
results <- sensitivityCalculation(simulation, outputPaths, parameterPaths)

sensivitityTimeProfiles(results) 
sensitivitySpiderPlot(results) 
```

> The results$SimulationResults contains no information about [Parameter](https://www.open-systems-pharmacology.org/OSPSuite-R/reference/Parameter.html) objects representing parameter paths. And these details are needed to create this plot. Before, when I was passing the dataframe, it contained all the details about parameter paths.

What info do you need from the `Parameter` objects? `SimulationResults` have a `Simulation` object that you could use to get the `Parameter` objects from paths... Or you just add the additional `parameterInfo`-list (data.frame, whatever) to the results output, where you gather all info (parameter paths, values, scale factors) you need.

**Comment by IndrajeetPatil** [comment]
Current state of the API. The primary function still returns dataframes, and that remains to be changed.

``` r
library(esqlabsR)
#> Loading required package: ospsuite
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000

simPath <- system.file("extdata", "Aciclovir.pkml", package = "esqlabsR")
simulation <- loadSimulation(simPath)
outputPaths <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
parameterPaths <- c(
  "Aciclovir|Lipophilicity",
  "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
  "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction"
)

set.seed(123)
results <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths
)

# class of object
class(results)
#> [1] "SensitivityAnalysis" "list"

# still returns dataframes
names(results)
#> [1] "tsData" "pkData"

# profile plot
sensitivityTimeProfiles(results)
#> Warning: Transformation introduced infinite values in continuous y-axis
#> Transformation introduced infinite values in continuous y-axis
```

![](https://i.imgur.com/S9NYZm1.png)

``` r
# spider plot
sensitivitySpiderPlot(results)
```

![](https://i.imgur.com/vs6qkqz.png)

<sup>Created on 2022-02-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
Before I make this change, I want us to consider the following scenario.

Let's say someone runs sensitivity analysis:

```r
results <- sensitivityCalculation(...)
```

Suppose they now wish to create Spider plots, but they don't like plots produced by `sensitivitySpiderPlot()` function. 
But, that's no problem; they can write their own function using _base_ or _ggplot2_, and just use the dataframe returned by `sensitivityCalculation()`.

```r
userCustomSpiderPlotFunction(results$pkData) 
```

Now, similarly, suppose they wish to create profile plots, but they don't like plots produced by `sensivitityTimeProfiles()` function. But `sensitivityCalculation()` returns `SimulationResults` object (in the proposed API). So now they will need to do extra work to extract dataframes from these objects, which they can then use for their custom plotting function:

```r
userCustomTimeProfilePlotFunction(???) 
```

Do you see this as an issue?

**Comment by IndrajeetPatil** [comment]
Okay, the returns for this function have changed now.

The function returns a list of `SimulationResults` objects (and additional details needed) instead of a time-series dataframe:

``` r
library(esqlabsR)
#> Loading required package: ospsuite
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000

simPath <- system.file("extdata", "Aciclovir.pkml", package = "esqlabsR")
simulation <- loadSimulation(simPath)
outputPaths <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
parameterPaths <- c(
  "Aciclovir|Lipophilicity",
  "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
  "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction"
)

set.seed(123)
results <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths
)

# class of object
class(results)
#> [1] "SensitivityAnalysis" "list"

# returns
names(results)
#> [1] "SimulationResults" "outputPaths"       "parameterPaths"   
#> [4] "pkData"

# profile plot
sensitivityTimeProfiles(results)
#> Warning: Transformation introduced infinite values in continuous y-axis
#> Transformation introduced infinite values in continuous y-axis
```

![](https://i.imgur.com/TmQ4p98.png)

``` r
# spider plot
sensitivitySpiderPlot(results)
```

![](https://i.imgur.com/1e4b1WL.png)

<sup>Created on 2022-02-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
@PavelBal For the same `variationRange`, the new `SimulationResults` return object is **18 times** heavier than the dataframe from previous API.

Is this expected?

# Previous results from `dataframe` return API

```r
library(ospsuite)
library(esqlabsR)

simPath <- system.file("extdata", "Aciclovir.pkml", package = "esqlabsR")
simulation <- loadSimulation(simPath)
outputPaths <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
parameterPaths <- c(
  "Aciclovir|Lipophilicity",
  "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
  "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction"
)

# extract the results into a list of dataframes
df_list <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths,
  variationRange = c(0.1, 1, 2)
)

lobstr::obj_size(df_list$tsData)
#> 445,328 B
```

# Current results from `SimulationResults` return API

``` r
library(ospsuite)
library(esqlabsR)

# run time-consuming simulations just once
simPath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
simulation <- loadSimulation(simPath)
outputPaths <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
parameterPaths <- c(
  "Aciclovir|Lipophilicity",
  "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
  "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction"
)

set.seed(123)
results <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths,
  variationRange = c(0.1, 2, 20)
)

lobstr::obj_size(results$simulationResults)
#> 7,880,080 B
```

<sup>Created on 2022-02-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
> The size of tsData in the default example is 2.7 Mb, which is crazy!

With the new API, the size of `simulationResults` for the default example is 8 Mb.

That said, I don't know if the _rate of change_ of size with respect to the length of `variationRange` vector is the same for these two objects. 

Based on just toying around with interactively, I am guessing not. The dataframe size seems to increase at a much faster rate compared to `simulationResults` when  the length of `variationRange` vector changes. So maybe it's worth having the latter API as the default if `variationRange` is expected to be a large vector in typical workflows.

**Comment by PavelBal** [comment]
I am very confused how the size is calculated...

Running with with 100 scale factors:

```
results <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths,
  variationRange = c(1:100)
)
```

Calculating the size - base vs losbtr

```
object.size(results$simulationResults)
lobstr::obj_size(results$simulationResults)
```

Now calculating the sizes of of subentries of `results$simulationResults` in base:

```
> object.size(results$simulationResults$`Aciclovir|Lipophilicity`)
58608 bytes
> object.size(results$simulationResults$`Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose`)
58608 bytes
> object.size(results$simulationResults$`Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction`)
58608 bytes
```

this makes sense for me, as it sums up to the size of `results$simulationResults`. Now the same with lobstr:

```
> lobstr::obj_size(results$simulationResults$`Aciclovir|Lipophilicity`)
8,177,904 B
> lobstr::obj_size(results$simulationResults$`Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose`)
8,177,904 B
> lobstr::obj_size(results$simulationResults$`Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction`)
8,177,904 B
```

each subentry is almost 8 mb, while the whole object is 10? I don't know what to make of it.

**Comment by IndrajeetPatil** [comment]
> each subentry is almost 8 mb, while the whole object is 10?

There is nothing special about this behaviour, either with our objects or with _lobstr_. You will get the same result with base-R and with a simple vector.

For example, even if every single element of a vector is 112 bytes and there are 3 elements, the total size is not 336 but 248 bytes. This is due to some optimizations in R that I don't fully understand.

``` r
y <- c("a", "b", "c")

object.size(y[1])
#> 112 bytes
object.size(y[2])
#> 112 bytes
object.size(y[3])
#> 112 bytes

object.size(y)
#> 248 bytes

library(lobstr)

obj_size(y[1])
#> 112 B
obj_size(y[2])
#> 112 B
obj_size(y[3])
#> 112 B

obj_size(y)
#> 248 B
```

<sup>Created on 2022-02-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

With respect to the differences in sizes of our particular objects, it can be due to one of the following [reasons](https://lobstr.r-lib.org/reference/obj_size.html):

![image](https://user-images.githubusercontent.com/11330453/155321730-003c2b37-19f2-41aa-9e35-f5fa0646dab4.png)

But, AFAIK, _lobstr_ is going to paint a more accurate picture since it accounts for additional things.
