### ISSUE TITLE
`sensitivityTimeProfiles`: improve text size

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#161]
It looks weird as many things do not fit in the figure

![image](https://user-images.githubusercontent.com/25903040/153629088-d154c7c1-edcf-406a-912d-6251b5fd29b7.png)

- The title
- Parameter paths (maybe multi-line?)
- Axis tics labels (e.g. the last 1500)

**Comment by PavelBal** [comment]
With this example:

```
simPath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
simulation <- loadSimulation(simPath)
outputPaths <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
parameterPaths <- c(
  "Aciclovir|Lipophilicity",
  "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
  "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction"
)

ls_results <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths
)
sensitivityTimeProfiles(sensitivityCalculation = ls_results)
```

When plotting to default output, it looks good (though the last subtitle is still clipped)

![image](https://user-images.githubusercontent.com/25903040/161230974-d371d9c5-eaf8-4b42-8163-42d49deb0d51.png)


When plotting to a file, most of the text is clipped.

![Profile_OutputPath1](https://user-images.githubusercontent.com/25903040/161231097-caf176ae-3f12-455b-9fd4-8c791c58c771.png)

Maybe the text size can be calculated based on total text width and output resolution/whatever, so it always fits?

**Comment by IndrajeetPatil** [comment]
>Maybe the text size can be calculated based on total text width and output resolution/whatever, so it always fits?

Unfortunately, this is not something the function can automate. This is exactly why we provide `width` and `height` parameters. 

The issue clipping of facet title should be fixed now:

``` r
library(esqlabsR)
#> Loading required package: ospsuite
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000

simPath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
simulation <- loadSimulation(simPath)
outputPaths <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
parameterPaths <- c(
  "Aciclovir|Lipophilicity",
  "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
  "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction"
)

ls_results <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths,
  variationRange = c(1, 3, 4)
)

sensitivityTimeProfiles(sensitivityCalculation = ls_results)
#> $`Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)`
```

![image](https://user-images.githubusercontent.com/11330453/162448755-25476e0a-d4d2-41a7-8259-8a3e7f4ae116.png)

**Comment by PavelBal** [comment]
> Unfortunately, this is not something the function can automate. 

Well, in theory ;) we could write a function that calculates the required text size based on the number of characters and the width of the plot etc... But that's fine as it is now, no need to invest more time in this. Thanks!
