### ISSUE TITLE
`sensitivityTimeProfiles`: better color selection

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#162]
With the current color gradient, it is not clear in which "direction" the colors move as the edges of the gradient look like they are "connected".

![image](https://user-images.githubusercontent.com/25903040/153629327-5f274c21-69cb-429e-9fb7-d6cbded51f22.png)

**Comment by PavelBal** [comment]
So select more distinct colors to move from to.

**Comment by IndrajeetPatil** [comment]
Here are all available palettes. Let me know which one you prefer, and I will make that the default:

``` r
library(esqlabsR)

simPath <- system.file("extdata", "Aciclovir.pkml", package = "esqlabsR")
simulation <- loadSimulation(simPath)
outputPaths <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
parameterPaths <- c(
  "Aciclovir|Lipophilicity",
  "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
  "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction"
)

set.seed(123)
results <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths
)

sensitivityTimeProfiles(results, palette = "Pastel 1")
```

![](https://i.imgur.com/E1feEoC.png)

``` r
sensitivityTimeProfiles(results, palette = "Dark 2")
```

![](https://i.imgur.com/CXa31rl.png)

``` r
sensitivityTimeProfiles(results, palette = "Dark 3")
```

![](https://i.imgur.com/87wtHr8.png)

``` r
sensitivityTimeProfiles(results, palette = "Set 2")
```

![](https://i.imgur.com/l1Wujho.png)

``` r
sensitivityTimeProfiles(results, palette = "Set 3")
```

![](https://i.imgur.com/HIz0F29.png)

``` r
sensitivityTimeProfiles(results, palette = "Warm")
```

![](https://i.imgur.com/vyniNMX.png)

``` r
sensitivityTimeProfiles(results, palette = "Cold")
```

![](https://i.imgur.com/kebIqUG.png)

``` r
sensitivityTimeProfiles(results, palette = "Harmonic")
```

![](https://i.imgur.com/mF71Yiz.png)

``` r
sensitivityTimeProfiles(results, palette = "Dynamic")
```

![](https://i.imgur.com/acHTS42.png)

<sup>Created on 2022-02-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
Any thoughts on this?

**Comment by PavelBal** [comment]
Let's try with `esqLABS_color`
https://github.com/esqLABS/esqlabsR/blob/3b13524235ccfa452552cefada4247f5ca452f26/R/utilities-figures.R#L18

Can you make it work?

**Comment by PavelBal** [comment]
Please also try the esqlabs-palette and show an example.

**Comment by IndrajeetPatil** [comment]
For now, I am choosing cold palette (see example above) as the default palette.

> Please also try the esqlabs-palette and show an example.

This doesn't work.

The function generates **discrete** colours. 

``` r
library(esqlabsR)
esqLABS_colors(10)
#>  [1] "#0D8DDA" "#142DDD" "#5F13E1" "#C911E4" "#E81098" "#EB1733" "#BF6A24"
#>  [8] "#C7CE20" "#65DC1C" "#26B042"
```

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

But we need **continuous** colours:

```r
colorspace::scale_color_continuous_qualitative(
  palette = "Cold",
  breaks = c(1, 10)
)
#> <ScaleContinuous>
#>  Range:  
#>  Limits:    0 --    1
```

This is because our scale is continuous:

![image](https://user-images.githubusercontent.com/11330453/162456435-8fd800c7-5f1c-46a8-b80e-a6927799a1a1.png)
