### ISSUE TITLE
sensitivitySpiderPlot: weird behavior of the legend

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#166]
When plotting directly to RStudio output, legend symbols are missing?

![image](https://user-images.githubusercontent.com/25903040/153631145-95f6dbd1-12d0-4fee-af2f-2f22a717cdc0.png)

However, they are displayed when e.g. clicking on "zoom" or output to file.

**Comment by IndrajeetPatil** [comment]
I can't reproduce this behavior. Maybe this was just a temporary issue?
