### ISSUE TITLE
What to do with `enumGetKey`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [esqLABS/esqlabsR#169]
``` r
library(esqlabsR)
#> Loading required package: ospsuite
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000
library(ospsuite.utils)
#> 
#> Attaching package: 'ospsuite.utils'
#> The following object is masked from 'package:esqlabsR':
#> 
#>     enumGetKey
```

<sup>Created on 2022-02-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
`ospsuite.utils::enumGetKey` now masks `esqlabsR::enumGetKey`:
https://esqlabs.github.io/esqlabsR/reference/enumGetKey.html

Should the latter be removed in favor of the former?

**Comment by PavelBal** [comment]
Check if the implementation is equal. If so - yes, remove it from esqlabsR.

**Comment by IndrajeetPatil** [comment]
There is no `ospsuite::getEnumKey()` function any more since it was moved to the utils package, so this function is not going to work anyway. Because there are neither tests nor examples for this function, this wasn't caught before.

https://github.com/esqLABS/esqlabsR/blob/d515e8a661e7ce797c47a59a5ebec01543c8c4b5/R/enum.R#L10-L12

So we can either remove this function from `esqlabsR` package namespace or re-export it from the utilities package.

**Comment by msevestre** [comment]
Do you even need to export it?

**Comment by PavelBal** [comment]
> There is no ospsuite::getEnumKey() function any more since it was moved to the utils package, so this function is not going to work anyway. 

Wait, I thought re-importing stuff from Utils into ospsuite should ensure that it can still be references as it was before?

**Comment by PavelBal** [comment]
Just remove it from `esqlabsr`, it is not used anywhere.

**Comment by IndrajeetPatil** [comment]
No, we just _import_ these functions in _ospsuite_ from the utilities package, we don't re-export them. So, for example, you won't find the `getEnumKey` function [here](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/NAMESPACE).

**Comment by IndrajeetPatil** [comment]
> Just remove it from esqlabsr, it is not used anywhere.

Got it.

**Comment by IndrajeetPatil** [comment]
I also don't see `enumPutList()` being used anywhere in the package. Should it stay or go?

**Comment by PavelBal** [comment]
> enumPutList()

keep it for now.
