### ISSUE TITLE
Remove `_R_CHECK_LENGTH_1_CONDITION_` check

### ISSUE THREAD

**Issue by IndrajeetPatil** [esqLABS/esqlabsR#196]
`_R_CHECK_LENGTH_1_CONDITION_` check has been removed from R 4.2 (release date: 22 April 2022): 
https://github.com/wch/r-source/commit/36e90ea062c4fad5343ae3a4ca122a3b266ad354

Reminder to get rid of this code:
https://github.com/esqLABS/esqlabsR/blob/42982d5e5c2fe35a794b93d94ad75624475ce409/R/zzz.R#L3

**Comment by PavelBal** [comment]
What did it do in the first place (I already forgot) and why has it been removed/what are the implications?

**Comment by IndrajeetPatil** [comment]
It used to issue a **warning** if `condition` in `if (condition) {}` was _not_ a logical scalar (e.g. `c(TRUE, TRUE)`).
From `R 4.2`, it produces an **error**.
We needn't worry about this because we don't currently see this warning anywhere, so we shouldn't have any error either.

I think the whole `zzz.R` file should be removed. 

Doing something like this is a bad idea because we are modifying the global state by changing options:

https://github.com/esqLABS/esqlabsR/blob/42982d5e5c2fe35a794b93d94ad75624475ce409/R/zzz.R#L2

If an R package modifies a global state, it should do so only temporarily.

**Comment by PavelBal** [comment]
> We needn't worry about this because we don't currently see this warning anywhere, so we shouldn't have any error either.

Will it always be an error, or must it be forced somehow (like with `_R_CHECK_LENGTH_1_CONDITION_`)?

> Doing something like this is a bad idea because we are modifying the global state by changing options:

Well we can see `zzz.R` as kind of a "coding standard" for esqlabs.

**Comment by IndrajeetPatil** [comment]
R core has decided to push this to `4.3`.
