### ISSUE TITLE
`sensitivityTimeProfiles` and `sensitivitySpiderPlot`: remove console outputs

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#203]
When calling `sensitivityTimeProfiles`, some unnecessary outputs are printed to the console. These should be removed (including warnings)

```
simPath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
simulation <- loadSimulation(simPath)
outputPaths <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
parameterPaths <- c(
  "Aciclovir|Lipophilicity",
  "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
  "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction"
)

ls_results <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths
)
> sensitivityTimeProfiles(sensitivityCalculation = ls_results) #PROFILE!!! Why sooo slow???

$`Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)`

Warning messages:
1: Transformation introduced infinite values in continuous y-axis 
2: Transformation introduced infinite values in continuous y-axis 
```

Also for `sensitivitySpiderPlot`:

```
> sensitivitySpiderPlot(sensitivityCalculation = ls_results)
$`Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)`

Warning message:
In Summary.unit(list(list(0, NULL, 8L), list(1, list(list(1, list( :
  reached elapsed time limit
```

**Comment by IndrajeetPatil** [comment]
No more warnings, but this comes at a cost:
All warnings need to be suppressed.

Warnings are generated not during plot creation, but during plot printing, which is not in our control. Turning off warnings globally gets rid of this issue. But, if this is not an acceptable solution, then we need to live with these warnings, because when concentrations values are nearly 0, log scale values are infinity, and that's what ggplot2 is complaining about. 

``` r
library(esqlabsR)

simPath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
simulation <- loadSimulation(simPath)
outputPaths <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
parameterPaths <- c(
  "Aciclovir|Lipophilicity",
  "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
  "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction"
)

ls_results <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths,
  variationRange = c(1, 5, 20)
)

sensitivityTimeProfiles(ls_results)
#> $`Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)`
```

![](https://i.imgur.com/utCUGHJ.png)

``` r
sensitivitySpiderPlot(ls_results)
#> $`Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)`
```

![](https://i.imgur.com/oz2dea3.png)

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by PavelBal** [comment]
> Turning off warnings globally gets rid of this issue. But, if this is not an acceptable solution, then we need to live with these warnings

What do you think of it? Should we leave them or hide for these functions?

Paths are still printed, I would remove them:

```
> sensitivitySpiderPlot(sensitivityCalculation = ls_results)
$`Organism|Age`

$`Organism|ArterialBlood|Plasma|Aciclovir`

$`Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)`
```

**Comment by IndrajeetPatil** [comment]
> What do you think of it? Should we leave them or hide for these functions?

I think we should leave them in. Turning warnings off globally is asking for trouble.

Let me give another try and see if there is any other possibility I have missed that might suppress warnings even while printing the plot. I doubt it, but never hurts to try.

> Paths are still printed, I would remove them:

I think this is vital information that we should not suppress. Without this, the users actually wouldn't know if a single plot was printed or multiple plots were printed. By default, RStudio prints plots on top of each other and users need to toggle between them. So, just looking at the RStudio _Plots_ panel, users wouldn't know if only the last plot was printed or multiple plots were printed.

**Comment by IndrajeetPatil** [comment]
Done.

``` r
library(esqlabsR)
#> Loading required package: ospsuite
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000

simPath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
simulation <- loadSimulation(simPath)
outputPaths <- c("Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)",
                 "Organism|Age",
                 "Organism|ArterialBlood|Plasma|Aciclovir")
parameterPaths <- c(
  "Aciclovir|Lipophilicity",
  "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
  "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction"
)

ls_results <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths,
  variationRange = c(1, 5, 20)
)

sensitivityTimeProfiles(ls_results)
#> [1] "Creating plot for path:Organism|Age"
```

![](https://i.imgur.com/nNwkuwK.png)

    #> [1] "Creating plot for path:Organism|ArterialBlood|Plasma|Aciclovir"

![](https://i.imgur.com/4fR7tnp.png)

    #> [1] "Creating plot for path:Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"

![](https://i.imgur.com/uR48r94.png)

<sup>Created on 2022-04-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
