### ISSUE TITLE
Sensitivity analysis with user defined pk parameters

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#205]
"Following non-standard PK parameters will not be calculated:
olol"

Check what exactly happens, this should be supported.

**Comment by IndrajeetPatil** [comment]
Coming from here:

https://github.com/esqLABS/esqlabsR/blob/460916f329ad455883a246e8b5578c2b4aa5b58a/R/utilities-sensitivity-Calculation.R#L299-L305

**Comment by IndrajeetPatil** [comment]
As you had specified here: https://github.com/esqLABS/esqlabsR/issues/173#issuecomment-1050869467
