### ISSUE TITLE
Appveyor: create "esqlabsR.zip"

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#213]
AppVeyor should also create a copy of the latest esqlabsR package without version numer, as it is done for other OSPS packages so the latest version can always be downloaded using the same link.

**Comment by PavelBal** [comment]
High prio.

**Comment by IndrajeetPatil** [comment]
The URL for artifact is:
https://ci.appveyor.com/api/projects/StephanSchaller/esqlabsr/artifacts/esqlabsR.zip
