### ISSUE TITLE
Make esqlabsR theme for default plot configuration

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#225]
Including sim results mapping to both color and line types. Should be loaded automatically when loading the package.

**Comment by PavelBal** [comment]
Wait, I though this is exactly why we have different themes - to specify such defaults? From Michaels comment I think he understands it the same way https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/871#issuecomment-1120195353

**Comment by IndrajeetPatil** [comment]
We don't have a `theme` parameter anymore (cf. https://github.com/Open-Systems-Pharmacology/OSPSuite-R/discussions/833#discussioncomment-2543512). We only take a plot configuration object.

**Comment by PavelBal** [comment]
But I thought that the default plot configuration is created based on the theme.

**Comment by IndrajeetPatil** [comment]
Nope, theme is not being used anywhere. 

We had considered the possibility of introducing  a new function that can convert an existing theme to a plot configuration object.
