### ISSUE TITLE
Create package "esqlabsRLegacy"

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#239]
The package should contain functionalities of esqlabsR that will be removed as obsolete (e.g. reading data from excel or figure creation). The package will not be further developed, should only be a snapshot of the current state to allow execution of old code (written for <=v3)

**Comment by PavelBal** [comment]
Contents:
 - DataMapping
 - DataMappingConfiguration
 - Plotable
 - PlotConfiguration
 - XYData
 - validateFileExists()
 - validateLength()
 - utilities-data-mapping
 - readOSPSTimeValues
 - figureAddLabel
 - .figureAddLegend
 - plotErrorBars
 - openOuptutDevice
 - closeOutputDevice
 - .isPoint
 - .isLine
 - GraphicsDevices
 - getQuantilesYData()
 - isCharInString()

esqlabsLegacyEnv:
- widthPerPlotMapping
- heightPerPlotMapping
- columnsToSplitDataBy
- XValuesColumn
- YValuesColumn
- YErrorColumn

Messages:
- errorFileNotFound 
- errorOutputPathNotFound
- warningLabelNotInDataMapping
- errorValuesAreNotPositive
- errorWrongLength
- errorMultipleMetaDataEntries

**Comment by IndrajeetPatil** [comment]
Shouldn't this be called `esqlabsRLegacy` if we are following lowerCamel case for naming packages?

**Comment by PavelBal** [comment]
Yes, why not.

**Comment by IndrajeetPatil** [comment]
Done:
https://github.com/esqLABS/esqlabsRLegacy

**Comment by IndrajeetPatil** [comment]
Why is `compareWithNA()` retained in v4?
It is not used [anywhere](https://github.com/esqLABS/esqlabsR/search?q=compareWithNA).

**Comment by IndrajeetPatil** [comment]
Ah, never mind. I see that most of the functions in [this section](https://esqlabs.github.io/esqlabsR/reference/index.html#miscllaneous) are not used inside the package. 
I guess they are useful for some internal workflows.
