### ISSUE TITLE
Plot grid title

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#256]
![RIF 100mg qd 14d_DC](https://user-images.githubusercontent.com/25903040/170002161-43330743-c16f-45ff-b5a5-ab0e05216554.PNG)

"RIF 100 mg qd 14d"

How to:

- Position it in the center
- Change its size?

I cannot find it in the `PlotGridConfiguration` class.

**Comment by IndrajeetPatil** [comment]
Closing in favour of https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/294
