### ISSUE TITLE
Plot grid labels size

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#257]
![RIF 100mg qd 14d_DC](https://user-images.githubusercontent.com/25903040/170002632-a9aa2546-0234-4cf0-9138-007b35fd1704.PNG)

How to change the size of the labels (a, b, c)?

**Comment by IndrajeetPatil** [comment]
Closing in favor of https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/294
