### ISSUE TITLE
Remove developer-focused dependency section of `README`

### ISSUE THREAD

**Issue by IndrajeetPatil** [esqLABS/esqlabsR#281]
`README` is for the user, and so this section sticks out like a sore thumb:

![image](https://user-images.githubusercontent.com/11330453/181026215-fbe340fb-b8f7-446a-97c8-5548040b0051.png)

**Comment by PavelBal** [comment]
What would be a better place for this info?

**Comment by IndrajeetPatil** [comment]
I am not sure if we need one? 

R package developer can figure out the needed packages just based on the `DESCRIPTION` file. It is redundant to list them, and maintain them.

Also, _esqlabsR_ can't be installed without _ospsuite_ being installed first. 
And _ospsuite_ already has an extensive documentation on installation/tools requirements.
