### ISSUE TITLE
Code coverage badge in README is outdated

### ISSUE THREAD

**Issue by IndrajeetPatil** [esqLABS/esqlabsR#284]
Not sure why, but it doesn't update after each commit. Therefore, it is misleading and should be removed. 

For example, currently the code coverage is > 53%, but it says it is 50%.

**Comment by PavelBal** [comment]
Hm

![image](https://user-images.githubusercontent.com/25903040/181234206-df477e4e-9266-4636-9f60-e82432c7f934.png)

**Comment by IndrajeetPatil** [comment]
Strange. 

Maybe I was looking at the cached version of the webpage. 

Good to know that it's working!

**Comment by IndrajeetPatil** [comment]
This is the problem. Code coverage doesn't seem to be computed for each commit. 

For example, no code coverage was run for [this](https://github.com/esqLABS/esqlabsR/pull/280) PR/commit. At any rate, not much we can do about it.

![image](https://user-images.githubusercontent.com/11330453/181237089-d0efa9ce-2c00-499e-ba69-ab46bf0633cb.png)
