### ISSUE TITLE
Clean "doc" folder

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#300]
The "doc" folder contains outdated documentation (e.g. the vignette "data-hanlding").

@IndrajeetPatil Could you clarify how the contents of this folder are generated?

**Comment by IndrajeetPatil** [comment]
Do you mean `/docs` folder?

I have already outlined the process [here](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/wiki/Generate-or-update-%7Bpkgdown%7D-website-for-the-package).

**Comment by PavelBal** [comment]
Lol, I have this folder only locally :D

**Comment by svavil** [comment]
> Do you mean `/docs` folder?
> 
> I have already outlined the process [here](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/wiki/Generate-or-update-%7Bpkgdown%7D-website-for-the-package).

Thanks for pointing this out for me.
