### ISSUE TITLE
Simulation fails sometimes with zero individuals

### ISSUE THREAD

**Issue by svavil** [esqLABS/esqlabsR#310]
I'm running the following code with the project structure set up exactly as in the example project. 

```
library(esqlabsR)
projectConfiguration <- createDefaultProjectConfiguration()
dataSheets <- "Laskin 1982.Group A"
observedData <- loadObservedData(projectConfiguration = projectConfiguration, sheets = dataSheets)
scenarioConfiguration <- ScenarioConfiguration$new(projectConfiguration)
OutputPaths <- enum(list(
  Aciclovir_PVB = "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
))
simulatedScenarios <- runScenarios(scenarioNames = c("TestScenario"), scenarioConfiguration = scenarioConfiguration, customParams = NULL, saveSimulationsToPKML = FALSE)
simulation <- simulatedScenarios$TestScenario$simulation
analysis <- sensitivityCalculation(simulation, OutputPaths, parameterPaths = "Aciclovir|Lipophilicity")
```

In several of the repeated runs, some of the simulations in the sensitivity analysis return zero individuals and not one, as expected. This seems to happen with a random simulation, not every time. When the error happens, the output of `analysis$simulationResults` might be, for example:

```
$`Aciclovir|Lipophilicity`
$`Aciclovir|Lipophilicity`$`0.1`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`0.2`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`0.3`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`0.4`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`0.5`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`0.6`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`0.7`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`0.8`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`0.9`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`1`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`2`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`3`
SimulationResults: 
   Number of individuals: 0 

$`Aciclovir|Lipophilicity`$`4`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`5`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`6`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`7`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`8`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`9`
SimulationResults: 
   Number of individuals: 1 

$`Aciclovir|Lipophilicity`$`10`
SimulationResults: 
   Number of individuals: 1 
```

**Comment by PavelBal** [comment]
My biggest concern is that the behavior is not deterministic.

This could be related to https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1016
https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/issues/146
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1672

**Comment by rwmcintosh** [comment]
I'm making a change in OSPSuite.Core to address this. It's a work-around for now. When SimModel gives results with no values there will be a flag set.

In my testing, the line below gives an error when results are returned with this flag set (and no results)

https://github.com/esqLABS/esqlabsR/blob/d44476614fb0484d23ec3fb565089c10f0a3f68c/R/sensitivity-calculation.R#L197

For now, my suggestion will be to remove, or flag, or something the failed results so they are not passed for further analysis

**Comment by svavil** [comment]
@rwmcintosh since the behavior is not deterministic, should we loop and re-run the analysis when a flag is returned?

**Comment by rwmcintosh** [comment]
> @rwmcintosh since the behavior is not deterministic, should we loop and re-run the analysis when a flag is returned?

That's what I was thinking. Basically, you'd need to assemble an appropriate set of results from a couple of runs, at least until we can figure out what else might be going on.

**Comment by rwmcintosh** [comment]
Wait for https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1672

**Comment by rwmcintosh** [comment]
@PavelBal @svavil you can update to the newest core after the nightly and you will then see that the R code will crash when there's no results returned from OSPSuite.Core.

**Comment by PavelBal** [comment]
This is fixed now.
