### ISSUE TITLE
Appveyor build fails at pandoc installation

### ISSUE THREAD

**Issue by svavil** [esqLABS/esqlabsR#311]
The current Appveyor build ([build link](https://ci.appveyor.com/project/StephanSchaller/esqlabsr/builds/44517728)) fails while installing Pandoc (corresponding to `cinst pandoc` instruction in `appveyor.yml`). The failure is due to error 429, `The remote server returned an error: (429) Too Many Requests. Too Many Requests`, which hints that this can be successful on a retry. 

I don't currently have the rights to re-initiate an Appveyor build for this repository. I think we need to re-run the Appveyor build for the latest commit in `develop` and see if it fixes the problem.

**Comment by PavelBal** [comment]
@msevestre @IndrajeetPatil Is there a way to trigger Appveyor build without a PR?

**Comment by svavil** [comment]
@PavelBal there should be one from the appveyor user interface for the people who have the appveyor rights. Some useful links for all of us

[How to cache chocolatey packages](https://www.appveyor.com/docs/build-cache/#caching-chocolatey-packages) 

[Re-build particular builds](https://github.com/appveyor/ci/issues/15)

**Comment by msevestre** [comment]
Yep there is a button to start a new build

**Comment by PavelBal** [comment]
I guess we need to wait for Stephan to be back to assign the rights.

**Comment by PavelBal** [comment]
Build runs again
