### ISSUE TITLE
plotIndividualTimeProfile() and the structure of DataCombined and dataSet

### ISSUE THREAD

**Issue by ReneGeci** [esqLABS/esqlabsR#321]
Hey,

if I want to use plotIndividualTimeProfile() then it may need information about the MW of the species to be able to plot the simulation and observed data together.

however, it seems the way it is structured right now, the (only?) way to provide the MW is that it has to be given in the observed dataSet in the DataCombined object.

But wouldnt it be possible (and easier for the user) to just pull the MW from the simulationResults that is provided to generate the DataCombined object?

**Comment by ReneGeci** [comment]
ah damn, i forgot that it may be difficult to map which MW should be taken if there are multiple molecules in the given simulation...
so feel free to close, if not feasible.

**Comment by PavelBal** [comment]
Interesting idea, but unfortunately `DataCombined` does not retain the underyling `Simulation` objects after results have been added. So you have to create your observed data with MW (e.g. by reading from excel where an MW column is present.
