### ISSUE TITLE
Unit Change 

### ISSUE THREAD

**Issue by maalbrec89** [esqLABS/esqlabsR#357]
Hi,

I wanted to change the units from h to minutes in the MoBi spatial structure element Organism|SmallIntestine|Small intestinal transit time. If I change units only, the values change as well but in a very couterintuitive way:

![image](https://user-images.githubusercontent.com/52818721/202388762-69c45116-1f9a-4d94-ab67-2d1e0e8bfcd7.png)

Those are just examples, If I change units, they can get very different values from time to time but may come to a certain set of values quite differnet from the start. I have to reopen MoBi to get the original setting.

I would expect:
0.09 day(s), 2.1h, and 126 min

**Comment by PavelBal** [comment]
Created an issue in MoBi-repository:

https://github.com/Open-Systems-Pharmacology/MoBi/issues/811
