### ISSUE TITLE
`plotConfigurationSheet`: column `foldDistance`

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#360]
The cells should be turned on/off based on the selected plot type.

Mind that the inputs may be vectors of numerics e.g. `c(1,2,3)`

**Comment by PavelBal** [comment]
For predicted vs ovbserved.


Check for observed vs simulated and observed vs time, residuals vs time etc.

**Comment by hannaei** [comment]
Should it not be only for plotObservedVsSimulated?

**Comment by PavelBal** [comment]
Yepp that's right, just checked. Wasnt sure.
