### ISSUE TITLE
`createPlotsFromExcel()` doesnt work when running only a subset of scenarios 

### ISSUE THREAD

**Issue by VanessaBa** [esqLABS/esqlabsR#370]
When running only a subset of the defined scenarios defined by `simulatedScenarios` the following error is thrown by 
```
createPlotsFromExcel(simulatedScenarios = simulatedScenarios,
                                observedData = observedData,
                                projectConfiguration = projectConfiguration)
```
```
Error in .validateDataCombinedFromExcel(dfDataCombined, simulatedScenarios,  : 
  The following scenarios are not present in `simulatedScenarios`: 
``` 
... followed by the list of many of the defined scenarios from the `Scenario.xlsx` but not all of them. Maybe it has something to do with the exportConfiguration?

**Comment by PavelBal** [comment]
Should be fixed with #373
