### ISSUE TITLE
The native pipe

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#38]
https://www.r-bloggers.com/2021/05/new-features-in-r-4-1-0/

**Comment by IndrajeetPatil** [comment]
I don't understand what this issue is about. Is it about starting to use the pipe operator in the codebase?

**Comment by PavelBal** [comment]
Ignore it, it was just a note to myself to maybe use the pipe operator.

**Comment by msevestre** [comment]
FYI: It does not work with v4.0 of R. You need a higher version. (4.1)

**Comment by PavelBal** [comment]
Not relevant
