### ISSUE TITLE
Rework `install-packages.R` file

### ISSUE THREAD

**Issue by Felixmil** [esqLABS/esqlabsR#431]
Since #418, installing dependencies is way easier, `install-packages.R` should reflect these changes.

**Comment by Felixmil** [comment]
When sourcing the `install-package.R` (or running the `installEsqLabsR()`) function, the user is prompted this:
```
> installEsqLabsR()
How do you want to install the packages? 

1: In local environment
2: Globally
```

The the installation is done through the following steps:
1. Install packages required for installation (pkgbuild, remotes, cli, renv if option 1 is picked)
2. Check if RTools is installed
3. Get Minimal PKSim
4. Install rClr
5. install esqlabsR and dependencies
6. Checking installation (of pksim and esqlabsR)
7. If available, run test simulations

The whole process is `{cli}` feedbacks:
```
✔ installing esqlabsR and dependencies. [5m 15.1s]
Loading required package: ospsuite
Loading required package: rClr
Loading the dynamic library for Microsoft .NET runtime...
Loaded Common Language Runtime version 4.0.30319.42000

! Test simulation files could not be found.
✔ Installation successful.
```

**Comment by Felixmil** [comment]
> The installation approach is in general very convenient. The drawback is of building the packages from source is that stored package version is always the one stored in `DESCRIPTION`, but all of our packages generate their version during AppVeyor build which is confusing at the end. Not sure how to handle this.

Indeed, I see two problems with that:
1) It is hard to specify exactly which version we want to install
2) The installed package version are not accurate

The first problem, we can define dependencies versions by specifying release github tag in `DESCRIPTION`:
```
Remotes:  
   Open-Systems-Pharmacology/OSPSuite-R@v11.2.251,
    ...
```
However, the version will still not show correctly
```r
> packageVersion("ospsuite")
[1] ‘11.2.0’
```

This problem will remain as long as we use Appveyor **builds** number as versioning identifiers. And this is why I'm advocating for using the `.9000` dev version marker and "manually" increase major, minor and patch versions directly in code.

In the meantime, there's still an intermediate solution for `{esqlabsR}`: use url remotes to target appveyor in `DESCRIPTION`:

```
Remotes:  
    url::https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-rutils/artifacts/ospsuite.utils_1.4.24.tar.gz,
...
```

```r
> packageVersion("ospsuite.utils")
[1] ‘1.4.24’
```

However, I would use this only for the `main`/released branch of the package only and keep targeting github's heads for dev branch

**Comment by Felixmil** [comment]
> `https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-r/artifacts/ospsuite.zip`
> 
> Like this, in this case it is always the latest build (from develop, I think).

It will not work for 2 reasons:
 1) The zip file is prebuilt package, which is incompatible with Remotes,
 2) We need to use the query ?pr=false at the end of the link to get the latest build from develop and not from PR.

**Comment by PavelBal** [comment]
Very much confusing :D

I really like the automatic version increase by AppVeyor. I cannot really imagine how to consistently manually increase the version when working on the same code in multiple branches. Let's say you and I start working on separate branches at the same time... How do we know which version to set manually?

And if  branch a) has been worked on for let's say 3 weeks, and in between 4 new branches have been merged already... You would have to manually update version of branch a) over and over? Seems very error prone.

**Comment by Felixmil** [comment]
You upgrade the version only when we **decide to make a release**. In the meantime, the version stays [major].[minor].[patch].9000

So for example:
- We work for 1 month on the package, with many branches. The package version is, 1.1.1.9000 for everyone during this period and all the new features are written in the `development` header of the `NEWS` file.
- After this month of work, we decide that the new features are stable enough and could benefit to the end users. So we increase the version (major, minor or patch depending on the scope), change the `development` header in `NEWS` to this new version and commit on develop/main with and add a git tag corresponding to this version. Also, dependencies/remotes can be fixed with current existing version to make it even more stable.
- Right after, a new commit is made that add a new `development` header in `NEWS` and add `.9000` to the version number. Dependencies are changed back to latest head etc...

This whole process can be nearly automated with usethis function. I'm not making this up, this is the process used by many organization like Posit of rOpenSci.

In the end we have:
- A clear series of release that are very stable and that we can easily communicate about
- Fixed dependencies version for stable releases,
- An easy way to install the latest stable release with `remotes::install_github(org/repo@*latest)`,
- The possibility for the dev AND users to always have the latest development version if they want to.

Appveyor build number is just used as reference for dev to get more granularity about the branch/dev version apart from the .9000 identifier.
