### ISSUE TITLE
use esqlabsR on Mac OS?

### ISSUE THREAD

**Issue by sandrinecharles** [esqLABS/esqlabsR#457]
Hi, is there any further plan to allow for the use of esqlabsR on Mac OS?

**Comment by PavelBal** [comment]
Dear @sandrinecharles , the `esqlabsR` package strongly depends on the `ospsuite-r` package which currently only supports Windows machines and (to some extent) Linux installations.

Our current plan is to support Linux fully, however, we do not have a timeline for that (might be by the end of this year). Having the whole R environment running on Mac OS would be beneficial, but we do not have Mac computers to be able to test it.

We would be happy to support if someone with MacOS computers would be willing to take over the testing part.

**Comment by PavelBal** [comment]
Closing. Pleas re-open or contact us directly if you are interested in supporting the migration to MacOS.
