### ISSUE TITLE
Change error message when there are duplicate labels in Plots.xlsx 

### ISSUE THREAD

**Issue by VanessaBa** [esqLABS/esqlabsR#500]
When you have duplicate entries for labels in a DataCombined definition in the Plots.xlsx then the following error is thrown
```
 Error in validateHasOnlyDistinctValues(names) : 
  Object has duplicated values; only unique values are allowed. 
```

A more specific error that points you to the labels would be helpful. Only after some digging ( `.validateDataCombinedFromExcel(()` ) I managed to get the more distinct error message
```
Error in .validateDataCombinedFromExcel(dfDataCombined, simulatedScenarios,  : 
  Missing values found in mandatory column 'label' of sheet 'DataCombined'. Fill in values to proceed. 
```
that helped me solve the problem.

**Comment by VanessaBa** [comment]
Internally available now.

**Comment by PavelBal** [comment]
Seems to be fixed
