### ISSUE TITLE
Corrupted pkml files

### ISSUE THREAD

**Issue by VanessaBa** [esqLABS/esqlabsR#502]
I cannot open any of my simulation files that were saved via the esqlabsR workflow using `saveScenarioResults()` in MoBi. However, I'm not using the latest release but some built provided by Pavel directly. I don't know if this problem existed before.

**Comment by VanessaBa** [comment]
v12 is needed to open the files. however, not a perfect solution from a client point of view.

**Comment by PavelBal** [comment]
nothing can be done
