### ISSUE TITLE
Error when executing `install-packages`

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#528]
When trying to install packages locally, I geh the following: 

<html>
<body>
<pre tabindex="0" aria-label="Console Output" role="document" class="GND-IWGDH3B" id="rstudio_console_output" style="font-family: &quot;Lucida Console&quot;, monospace; font-size: 13.3333px; outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; line-height: 1.2; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: -webkit-left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span tabindex="-1" class="GND-IWGDI3B" role="document" style="outline: none;"><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">The following required packages are not installed:
- esqlabsR
- openxlsx
- ospsuite
- ospsuite.utils
Packages must first be installed before renv can snapshot them.
Use `renv::dependencies()` to see where this package is used in your project.

What do you want to do? 

1: Snapshot, just using the currently installed packages.
2: Install the packages, then snapshot.
3: Cancel, and resolve the situation on your own.

</span></span><span tabindex="-1" class="GND-IWGDI3B" role="document" style="outline: none;"><span class="GND-IWGDO3B ace_keyword" style="color: blue; white-space: pre; user-select: text;">Selection: </span><span class="GND-IWGDN2B ace_keyword" style="color: blue;">2
</span><div class="GND-IWGDPHD ace_console_error" style="position: relative; overflow: hidden; margin: 5px 5px 5px 0px; padding: 5px 0px 5px 10px; white-space: pre-line; background-color: rgb(230, 230, 230);"><div class="GND-IWGDAID" style="top: 5px; float: right; margin-right: 10px; margin-left: 5px; margin-bottom: 15px; line-height: 10.6667px; position: relative; user-select: none;"><div><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAaElEQVR42mNgwAXWv8sEY4rA2vd+DOve/wFjEJsssOGjOdCA/ygYJEYS2PhRBcMQGAbJEQVWfRbFaQgMg9TgBZufcRE0BIZBarG75D8z0YbAXQbUgwFINQSGCQKyNY4aRLoFw9iggQYAE6xnKErSS9EAAAAASUVORK5CYII=" width="18" height="18" class="GND-IWGDBID show_traceback_image" alt="" aria-hidden="true" style="cursor: pointer; width: 9px !important; height: 9px !important;"> <a class="GND-IWGDCID show_traceback_text" style="font-family: &quot;Segoe UI&quot;, serif; font-size: 10.6667px; opacity: 0.5; cursor: pointer;">Show Traceback</a></div><div><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAABU0lEQVR42pWUP0vEMBjGo4uz2rQO4iS66KCC4OSoi99C/ATu9zn8AKII16QOgoLgoCD+WR28tUnuThQUp0OvPm+8P9ZrSxJ4hjZ9fn2TPG8YKxlT9XQ2FPqAC6O40B3oKojNJvMZ08Ksw/gGZf/0FUi16wSZPFVzMLQLIH11wjjdGDEGdbXKatn44FloUQHp634AgNcy8PKCS30dyeYyT9SKA8SKlh/FzSXyEoOxLBtDFXu95dy5ggKhbslD3r8rYmHSijDx7gqyPz5pz4zuMqh0Kh6gl5zfw1ipXAA9zd+F+Zk/a0xgsusKQupfS8OIdmh4VPRYCPk9NS/QM3mGhGGOWij30B1kjsljcwQGndo5dEPJtpUJdekAeqK42G6A1yYbxLVcr8XpAiY+KyDdUOqtXK8Ro3DTY71dAgPE7HvdSUGiFrk0RzB/9BL/gLtop+z7HzowRJ/sYbqcAAAAAElFTkSuQmCC" width="18" height="18" class="GND-IWGDBID rerun_image" alt="" style="cursor: pointer; width: 9px !important; height: 9px !important;"> <a class="GND-IWGDCID rerun_text" style="font-family: &quot;Segoe UI&quot;, serif; font-size: 10.6667px; opacity: 0.5; cursor: pointer;">Rerun with Debug</a></div></div><div class="GND-IWGDDID GND-IWGDB3B  ace_constant" style="display: inline; overflow-wrap: break-word; word-break: break-word; color: rgb(197, 6, 11);"><span>Error: package 'esqlabsR' is not available</span></div><div class="GND-IWGDEID stack_trace" aria-hidden="true" style="margin-top: 0.5em; margin-left: 0.3em; display: block;">

28. | stop(sprintf(fmt, ...), call. = call.)
-- | --

</div></div><span class="GND-IWGDH3B xtermColor1" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(204, 0, 0) !important;">✖</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;"> Verify PKSim installation </span><span class="GND-IWGDH3B xtermColor249" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(178, 178, 178) !important;">[28.4s]</span></span></pre>
</body>
</html>

**Comment by PavelBal** [comment]
Also `remotes::install_github("esqLABS/esqlabsR")` constantly failing.

**Comment by Felixmil** [comment]
The error should be before when this was executed

```r
  remotes::install_github("esqLABS/esqlabsR",
                 quiet = TRUE,
                 build = TRUE
  )
``` 

Also, we may want to switch to `remotes::install_github("esqLABS/esqlabsR*release")` to get latest released version instead of dev.

**Comment by Felixmil** [comment]
> Also `remotes::install_github("esqLABS/esqlabsR")` constantly failing.

How ? I've been using this morning for BI's servers and it works.

**Comment by PavelBal** [comment]
> Also, we may want to switch to remotes::install_github("esqLABS/esqlabsR*release") to get latest released version instead of dev.

Yes, by now this might be a good practice.

> How ? I've been using this morning for BI's servers and it works. What's the error ?

Download failed, wtf... Could it be because I swithched to two-factor authentication for GitHub?

**Comment by Felixmil** [comment]
> Yes, by now this might be a good practice.
Opened #529 



> Download failed, wtf... Could it be because I swithched to two-factor authentication for GitHub?

I also enabled it but had no problem with it. Do you have a "GITHUB_PAT" defined in your `Renviron` ? If no, follow this: https://gist.github.com/Z3tt/3dab3535007acf108391649766409421

**Comment by PavelBal** [comment]
Still can't get it running...

utils::download.file("https://api.github.com/repos/esqLABS/esqlabsR/tarball/HEAD", destfile = "../boom.tar.gz")
trying URL 'https://api.github.com/repos/esqLABS/esqlabsR/tarball/HEAD'
downloaded 29.0 MB

```
Error in utils::download.file("https://api.github.com/repos/esqLABS/esqlabsR/tarball/HEAD",  : 
  download from 'https://api.github.com/repos/esqLABS/esqlabsR/tarball/HEAD' failed
In addition: Warning message:
In utils::download.file("https://api.github.com/repos/esqLABS/esqlabsR/tarball/HEAD",  :
  URL 'https://codeload.github.com/esqLABS/esqlabsR/legacy.tar.gz/HEAD': Timeout of 60 seconds was reached
```

Manually opening `https://api.github.com/repos/esqLABS/esqlabsR/tarball/HEAD` in browser starts to download with extremely slow speed.

**Comment by PavelBal** [comment]
This seems to be completely random... Most of the time it just fails with a timeout, sometimes it downloads within two seconds.

**Comment by PavelBal** [comment]
Closing, this is not reproducible and does not make any sense to me.
