### ISSUE TITLE
Population simulation aggregation: number of SD in aggregation "arithmetic" and "geometric"

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#530]
- Add argument "xSD" (or whatever)
- New column in excel?
- Document in the vignette what the defaults are

**Comment by Felixmil** [comment]
See https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/1302

**Comment by PavelBal** [comment]
Implement for Plots.xlsx

**Comment by Felixmil** [comment]
See #544
