### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Felixmil** [esqLABS/esqlabsR#540]
[esqLABS utilities package • esqlabsR](https://esqlabs.github.io/esqlabsR/) --> in the second paragraph, PBK --> PBPK

**Comment by PavelBal** [comment]
PBK = Physiologically Based Kinetics, which is a broader term than "PK = Pharmacokinetics". Supposed to reflect that we not only work with pharma.

**Comment by Felixmil** [comment]
ping @GhazalMontaseri
