### ISSUE TITLE
Replace `IndividualId` tabs with one `IndividualsParameters` tab

### ISSUE THREAD

**Issue by Felixmil** [esqLABS/esqlabsR#557]
Instead of creating one tab for each Individual to set parameters in the `Individuals.xlsx`, a single tab (called `IndividualsParameters` for example) would be easier to handle programmatically. I don't think it is problematic from the user side to have only one tab for that.

**Comment by Felixmil** [comment]
Instead of having only these columns:

Container   Path | Parameter Name | Value | Units
-- | -- | -- | --

add, `IndividualId` column

IndividualId  | Container   Path | Parameter Name | Value | Units
-- | -- | -- | -- | --

**Comment by PavelBal** [comment]
There is one major issue with this - the current structure can be imported in MoBi. Having all the parameters in one sheet will not be compatible with MoBi, so no.
