### ISSUE TITLE
Rename `projectConfiguration$paramsFile` by `projectConfiguration$modelParamsFile`

### ISSUE THREAD

**Issue by Felixmil** [esqLABS/esqlabsR#558]

**Comment by Felixmil** [comment]
No direct complaints. But since we will already break the `PopulationParams.xlsx` file  path in the next release, better harmonize now.

**Comment by PavelBal** [comment]
Okay then.

**Comment by PavelBal** [comment]
https://github.com/esqLABS/esqlabsR/pull/635
