### ISSUE TITLE
Add link to latest built artifact

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#591]
As we used AppVeyor, we could always download the latest build of the package by going to the "Artifacts" tab. Can we add the link to the latest artifact built with GitHub actions from the main branch to the README?

![image](https://github.com/esqLABS/esqlabsR/assets/25903040/6c3614c0-0cc3-4edd-9160-adb98533afdb)

**Comment by Felixmil** [comment]
The artifact corresponding to this is the `built_package.zip` file  which contains the built version of our package and is generated on successful runs of [this action](https://github.com/esqLABS/esqlabsR/actions/workflows/R-CMD-check.yaml).

![image](https://github.com/esqLABS/esqlabsR/assets/34234913/335bcc5a-905a-499c-ad8f-b47a80134288)

![image](https://github.com/esqLABS/esqlabsR/assets/34234913/f8a16117-c77c-409b-b4ba-01f7fd6aa3af)

According to [this issue](https://github.com/actions/upload-artifact/issues/51), there is no way to get a permalink for an artifact created by an action using GitHub API currently.

But we can use this site which provides an external alternative to permalinks: https://nightly.link

By pasting the link to the workflow that is in charge of generating the built package into this site, it generates the following link Which will always redirect to download the latest successful build of main branch. https://nightly.link/esqLABS/esqlabsR/workflows/R-CMD-check.yaml/main/built_package.zip



How do we want to provide it in the README ? Here's our options:

- A simple link in text:
  > Download the latest build [here](https://nightly.link/esqLABS/esqlabsR/workflows/R-CMD-check.yaml/main/built_package.zip).

- A download button
  > [![Download Latest Build](https://custom-icon-badges.demolab.com/badge/-Download-blue?style=for-the-badge&logo=download&logoColor=white "Download Latest Build")](https://nightly.link/esqLABS/esqlabsR/workflows/R-CMD-check.yaml/main/built_package.zip)
  > ```
  > [![Download Latest Build](https://custom-icon-badges.demolab.com/badge/-Download-blue?style=for-the-badge&logo=download&logoColor=white "Download Latest Build")](https://nightly.link/esqLABS/esqlabsR/workflows/R-CMD-check.yaml/main/built_package.zip)
  > ```

**Comment by Felixmil** [comment]
Implemented in #592
