### ISSUE TITLE
Request for sensitivitySpiderPlot() to allow absolute values - y axis

### ISSUE THREAD

**Issue by wilbertdew** [esqLABS/esqlabsR#597]
sensitivitySpiderPlot() normalizes the output (y-axis) for the references value and it uses the column "PercentChangePK" from the sensitivity calculation. I would like to be able to choose for the alternative where I can also plot the absolute values as available by the column PKParameterValue in the sensitivity calculation output dataframe.

Along the same lines, it would be helpful (but less critical for me at the moment) to do the same for the x-axis and make the normalization optional. the absolute values are here also already available in the sensitivity calculation output data frame in the column "ParameterValue"

These options can give weird-looking and unhelpful plots if you put multiple parameters at the same time, but they can be helpful to plot the same parameter in different scenarios

**Comment by PavelBal** [comment]
Wilber has a code for this in place.

**Comment by PavelBal** [comment]
How-to in signature?
