### ISSUE TITLE
SA: Time Profiles legend colors

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#606]
For this graph, it would be useful if the color scale could be dependent on linear parameter value variations or variations on the log domain: i.e. if the parameter value changes from 0.1 to 10, the middle of the color gradient should be 1 (i.e. log domain), while if the parameter changes from 0.5 to 1.5, the middle should also be 1 (i.e. linear domain). This could be automatic, but a manual setting should be fine as well

**Comment by rengelke** [comment]
This issue was fixed by PR #123.
