### ISSUE TITLE
SA spider plot: `DefaultPlotConfiguration` properties that must be supported

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#619]
List all properties of DefaultPlotConfiguration, that will be supported by the SA spider plot.

**Comment by Laura-Villain** [comment]
Selected list:


linesColor:
 pointsColor:
caption: NULL
xLabel         = "Input parameter value [% of reference]",
  yLabel         = NULL,
  title          = unique(data$OutputPath),
legendPosition = "bottom",
  linesSize      = 1.4,
  pointsSize     = 2,
  xAxisScale     = "log",
  yAxisScale     = "lin",
  yAxisTicks
 
legendTitle: NULL
linesAlpha: 0.75
linesLinetype: NULL
pointsAlpha: 0.75
pointsShape: circle diamond triangle square invertedTriangle cross th ...
subtitle: NULL
xAxisLimits: NULL
yAxisLimits: NULL
xValuesLimits: NULL
yValuesLimits: NULL
xLabel: NULL
yLabel: NULL
