### ISSUE TITLE
Function signature for `sensitivityTimeProfiles

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#624]
E.g.:

```
sensitivityTimeProfiles(
  sensitivityCalculation,
  outputPaths = NULL,
  parameterPaths = NULL,
DefaultPlotConfiguration
)
```

**Comment by PavelBal** [comment]
https://github.com/esqLABS/esqlabsR/issues/259

**Comment by Laura-Villain** [comment]
sensitivityTimeProfiles(
  sensitivityCalculation,
  outputPaths = NULL,
  parameterPaths = NULL,
data = dataSets object
DefaultPlotConfiguration
)
