### ISSUE TITLE
Function signature for `sensitivitySpiderPlot`

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#625]
E.g. 

```
sensitivitySpiderPlot(
  sensitivityCalculation,
  outputPaths = NULL,
  parameterPaths = NULL,
  pkParameters = NULL,
DefaultPlotConfiguration
)
```

**Comment by PavelBal** [comment]
https://github.com/esqLABS/esqlabsR/issues/597

**Comment by rengelke** [comment]
sensitivitySpiderPlot(
  sensitivityCalculation,
  outputPaths = NULL,
  parameterPaths = NULL,
  pkParameters = NULL,
  yAxisType = "percent", "absolute"
  xAxisTYpe = "percent", "absolute"   BUT split by ParametrePath
  DefaultPlotConfiguration
)
