### ISSUE TITLE
Rename `Parameters` folder into `Configurations`?

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#631]
As by now the files within this folder contain much more than just parameters?

**Comment by PavelBal** [comment]
@Felixmil @dlefaudeux @Laura-Villain What do you think?

**Comment by Felixmil** [comment]
Either that or `SimulationSettings` or something similar

**Comment by PavelBal** [comment]
No, `SimulationSettings` has a well-defined meaning in OSP software and does not include parametrization.

**Comment by PavelBal** [comment]
https://github.com/esqLABS/esqlabsR/pull/635
