### ISSUE TITLE
Harmonize `Configuration` excel file names

### ISSUE THREAD

**Issue by Felixmil** [esqLABS/esqlabsR#633]
Some ends with `Parameters`, others don't:
![image](https://github.com/esqLABS/esqlabsR/assets/34234913/dec32729-8b80-4d0c-a905-eafd28848430)

Some are singular, other plural also.

Shall we harmonize to:
```sh
Configurations/
- Applications
- Individuals
- ModelParameters
- Plots
- Populations
- PopulationsCSV/
- Scenarios
```

**Comment by PavelBal** [comment]
https://github.com/esqLABS/esqlabsR/pull/635
