### ISSUE TITLE
rename `createDefaultProjectConfiguration` to `createProjectConfiguration`

### ISSUE THREAD

**Issue by Felixmil** [esqLABS/esqlabsR#634]
I don't think `Default` is necessary.

- [x] create `createProjectConfiguration()`
- [x] deprecate `createDefaultProjectConfiguration()` with warning and pass to `createProjectConfiguration`

**Comment by PavelBal** [comment]
Yes

**Comment by PavelBal** [comment]
https://github.com/esqLABS/esqlabsR/pull/635
