### ISSUE TITLE
PI: compare before/after PI on plots

### ISSUE THREAD

**Issue by Laura-Villain** [esqLABS/esqlabsR#638]
I would like to be able to see the plot compared before and after PI, to observe visually what is the difference. 
The priority would be on individual time profile, but all plots produced by a PI  could also benefit from that. 

The implementation would simply to have the two curves/points in a different color with a legend

**Comment by PavelBal** [comment]
@Laura-Villain please open all PI related issues in the PI repo https://github.com/Open-Systems-Pharmacology/OSPSuite.ParameterIdentification

**Comment by PavelBal** [comment]
Yes please. I cannot transfer then to another organization (OSP).
