### ISSUE TITLE
`sensitivitySpiderPlot` - axis scaling settings

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#643]
Right now, axis scaling can be defined in the signature AND in the plot configuration. Discuss with users what would be the best approach:

1) value in signature overrides configuration
2) value in configuration overrides signature
3) remove axis scaling setting from the signature
4) else

**Comment by rengelke** [comment]
@Laura-Villain @dlefaudeux 
Thank you for the constructive discussion regarding the implementation of axis scaling. 

As discussed, we will keep the ability to define axis scaling directly in the function signature, as it is an important parameter which should be accessed easily without the need to set it up in `defaultPlotConfiguration`. 

In summary, `xAxisScale`and `yAxisScale` parameter settings will follow this hierarchy:
1.  Plotting function signature
2. `defaultPlotConfiguration`
3. specific plot configuration set up inside the plotting function
