### ISSUE TITLE
Get rid of `purrr::map_dfr` etc

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#678]
`purrr::map_dfr`  is superseded, replace it by the more up-to-date approaches.

Or better just get rid of all map purr etc

**Comment by Felixmil** [comment]
Why do we want to get rid of `{purrr}` ?

**Comment by Felixmil** [comment]
What do you mean ? Adding a  `browser()` call to pause inside the function used by `{purrr}` works perfectly:

```r


library(purrr)

f <- function(x) {
  browser()
  y <- 20
  if (x > 5) {
    stop("!")
  } else {
    x
  }
}


purrr::map(1:10, f)
```
