### ISSUE TITLE
Update documentation about "Install PK-Sim"

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#682]
https://esqlabs.github.io/esqlabsR/articles/install-pksim.html

- Mention that only required for `esqlabsR` version lower than version xxx.
- Provide a link to PK-Sim core files from AppVeyor (e.g. for developers)

**Comment by Felixmil** [comment]
I realize now that this is more related to `{ospsuite}` than `{esqlabsR}`.

I will remove this page from here and add it to `{ospsuite}` documentation.

**Comment by Felixmil** [comment]
see https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1455
