### ISSUE TITLE
functions to retire in light of new data import functionality

### ISSUE THREAD

**Issue by IndrajeetPatil** [esqLABS/esqlabsR#70]
@PavelBal These can be listed in this issue.

**Comment by PavelBal** [comment]
## Loading observed data
In `esqlabsR`, data are currently loaded from excel with the function `readOSPSTimeValues()` and stored as `XYData` objects. This will be replaced by the ospsuite functionality `loadDataSetsFromExcel()` that returns objects of class `DataSet`.
 -  `readOSPSTimeValues()`
 - `XYData`
 - `DataConfiguration`

gets replaced by 
- `DataSet`
- `loadDataSetsFromExcel()`

Check out the tests `test-data-set` and `test-utilities-data-set` for examples.

## Figure creation
The functionality of grouping data sets and creating figures in `esqlabsR` is implemented in

- `DataMapping` -> will be (partially) replaced by `DataGrouping` in `ospsuite-r` (see the document with the proposed concept)
- `DataMappingConfiguration`
- `Plotable` as a superclass of `XYData`
- `PlotConfiguration` will be replaced by the different configuration-classes as proposed
- `utilities-data-mapping` is basically the logic how to create figures out of `DataMapping` -> will be replaced by the different `plot...()` functions as proposed.
- Several functions from `utilities-figures` will also be removed. I would leave `esqLABS_colors`, `figureAddLabel`, `col2hsv`, `plotErrorBars`.

**Comment by PavelBal** [comment]
Closing in favor of https://github.com/esqLABS/esqlabsR/issues/238
