### ISSUE TITLE
bug in extendPopulationByUserDefinedParams

### ISSUE THREAD

**Issue by KatrinCoboeken** [esqLABS/esqlabsR#706]
In the function extendPopulationByUserDefinedParams  my code crashes at line   validateIsNumeric(meanValues, sdValues). 
sdValues is interpretaed as the second input parameter of ospsuite.utils::validateIsNumeric nullAllowed

**Comment by Felixmil** [comment]
Hi Katri, sorry to ear that. Could you please provide a minimal reproducible example ? (using `{reprex}` for example)

**Comment by KatrinCoboeken** [comment]
population <- ospsuite::loadPopulation(system.file("extdata", "SimResults_pop.csv", package = "ospsuite"))

esqlabsR::extendPopulationByUserDefinedParams(
  population = population, 
  parameterPaths = c('Organism|Kidney|GFR'),
  meanValues = 0.12, 
  sdValues = 0,
  distributions = 'Normal'
)
#> Error: base::tryCatch: argument 'nullAllowed' is of type 'double', but expected 'logical'!

**Comment by Felixmil** [comment]
Thank you for finding this and taking time to provide a reprex. This issue was solved in #708 and will be merged into `main` soon !
