### ISSUE TITLE
bug in extendPopulationFromXLS

### ISSUE THREAD

**Issue by KatrinCoboeken** [esqLABS/esqlabsR#707]
In function extendPopulationFromXLS columnNames should be   

columnNames <- c(
    "Container Path", "Parameter Name", "Mean",
    "SD", "Distribution"
  )

But later on they are referenced with dots:
      paramPath <- paste(data[["Container.Path"]][[i]], data[["Parameter.Name"]][[i]], sep = "|")

**Comment by Felixmil** [comment]
Will be fixed in #708
