### ISSUE TITLE
Move CI stuff to a separate branch until we figure out how to properly use it

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#83]

**Comment by PavelBal** [comment]
And also remove rClr from tools... I think we can install it from the release link, I don't want to overload the package.

**Comment by IndrajeetPatil** [comment]
But I think we need it in the `tools` folder for CI to work, otherwise `AppVeyor` doesn't know where to download it from as the package is also not on CRAN

https://github.com/esqLABS/esqlabsR/blob/00d8638dd420d3e6d40a74e6797810a3d97ecaeb/appveyor.yml#L40

**Comment by IndrajeetPatil** [comment]
I am not sure what you mean by 

> until we figure out how to properly use it

We _are_ already using it properly and the CI even downloads the dependencies. It falters during the R CMD Check with a strange error, but that's a separate [issue](https://github.com/esqLABS/esqlabsR/issues/85). It's not because we are not using CI properly.

**Comment by IndrajeetPatil** [comment]
Closing in favor of #85
