### ISSUE TITLE
AppVeyor issue

### ISSUE THREAD

**Issue by IndrajeetPatil** [esqLABS/esqlabsR#85]
@msevestre Do you have any experience with error like this in `AppVeyor` builds? 
I've never experienced something like this before, so not sure how to fix it.

https://ci.appveyor.com/project/IndrajeetPatil/esqlabsr/builds/40950527/job/4hm67gc36c7imgfk#L963

![image](https://user-images.githubusercontent.com/11330453/135229759-dbd8231a-8934-41c6-aa40-897f09ab8f8e.png)

The package version is completely fine, so not sure why it thinks it's malformed:
https://github.com/esqLABS/esqlabsR/blob/42a85204ce4e0b8c479d69579d84a7633c348b1f/DESCRIPTION#L4

**Comment by msevestre** [comment]
@IndrajeetPatil @PavelBal There is a bunch of stuff in the rakefile.rb related to downloading PKSim, creating a Linux branch etc.. do you need this? If not, I can clean up the file a bit

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/135306687-7f11970a-7714-47e1-9982-7e0c0637ad26.png)

This version is corrupted. That's why. It's being injected into the file dynamically. We are using a hack to ensure that the versions are always the same. between R, PKSim MoBi etc... probably not implemented properly.

I can probably fix this...

**Comment by IndrajeetPatil** [comment]
> There is a bunch of stuff in the rakefile.rb related to downloading PKSim, creating a Linux branch etc.. do you need this?

I don't think so. I don't know `Ruby`, so I just ported over everything as it was from `{ospsuite}` package, lest something broke.

**Comment by msevestre** [comment]
ok let me clean that up

**Comment by msevestre** [comment]
ok the build is fixed. But you do not install ospsuiteR. How is this supposed to work? Or is esqlabR not using ospsuiteR?

**Comment by msevestre** [comment]
ERROR: dependency 'ospsuite' is not available for package 'esqlabsR'
* removing 'C:/Users/appveyor/AppData/Local/Temp/1/RtmpYF99QE/Rinst102074f5496e/esqlabsR'
      -----------------------------------
ERROR: package installation failed
Command exited with code 1
7z a failure.zip *.Rcheck\*

**Comment by PavelBal** [comment]
I would prefer not to have the compiled ospsuite-r in tools, but if it does not work without than we have to live with it... I maybe find out why installing from repo does not work in the future.
