### ISSUE TITLE
protect `main`/`master` and `develop` branches

### ISSUE THREAD

**Issue by IndrajeetPatil** [esqLABS/esqlabsR#87]
Just like in the `OSP` repositories, although I am not sure what settings to change to achieve this:

![image](https://user-images.githubusercontent.com/11330453/135269931-04df89f5-fc64-48fc-afe9-e11f39c0c69d.png)

**Comment by msevestre** [comment]
I can help

**Comment by PavelBal** [comment]
@msevestre Yeah, how do I protect `main` and `develop` with one rule?

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/135306407-85b6cd7d-cf7d-422b-8483-f5027f2d7d11.png)

Can't help. No access

**Comment by IndrajeetPatil** [comment]
Pavel has made the necessary change, I think. Because the develop branch is now protected.
