### ISSUE TITLE
Delete tests/data/BigDataFile.xlsx

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#92]

**Comment by PavelBal** [comment]
In any of the next PRs (doesnt make sense to create a new PR for that)

**Comment by IndrajeetPatil** [comment]
I don't see any file called `BigDataFile.xlsx` here:
https://github.com/esqLABS/esqlabsR/tree/develop/tests/data

Am I missing something?

**Comment by PavelBal** [comment]
Damn, it was only a local copy not synched... Everything fine then ;)
